# Generated by Django 5.2.12 on 2026-05-30 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("financials", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogoIndicador",
            fields=[
                (
                    "id_catalogo_indicador",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("codigo", models.CharField(max_length=50, unique=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("formula", models.TextField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "catalogo_indicador",
            },
        ),
        migrations.CreateModel(
            name="IndicadorFinanciero",
            fields=[
                ("id_indicador", models.AutoField(primary_key=True, serialize=False)),
                (
                    "score_financiero",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "clasificacion_riesgo",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "recomendacion",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("resumen_interpretativo", models.TextField(blank=True, null=True)),
                ("fecha_calculo", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reporte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indicadores",
                        to="financials.reportefinanciero",
                    ),
                ),
            ],
            options={
                "db_table": "indicador_financiero",
            },
        ),
        migrations.CreateModel(
            name="ValorIndicador",
            fields=[
                ("id_valor", models.AutoField(primary_key=True, serialize=False)),
                ("valor", models.DecimalField(decimal_places=6, max_digits=18)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "catalogo_indicador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="valores",
                        to="analytics.catalogoindicador",
                    ),
                ),
                (
                    "indicador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valores",
                        to="analytics.indicadorfinanciero",
                    ),
                ),
            ],
            options={
                "db_table": "valor_indicador",
            },
        ),
    ]
