# Generated by Django 5.2.12 on 2026-05-30 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
        ("financials", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecomendacionIA",
            fields=[
                (
                    "id_recomendacion",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("recomendacion", models.CharField(max_length=100)),
                ("justificacion", models.TextField()),
                ("score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recomendaciones",
                        to="financials.empresa",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recomendaciones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "recomendacion_ia",
            },
        ),
        migrations.CreateModel(
            name="SimulacionFinanciera",
            fields=[
                ("id_simulacion", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_simulacion", models.CharField(max_length=200)),
                ("parametros", models.JSONField()),
                ("resultado", models.JSONField()),
                (
                    "score_confianza",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simulaciones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "simulacion_financiera",
            },
        ),
    ]
