# Generated by Django 5.2.12 on 2026-05-30 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionSistema",
            fields=[
                (
                    "id_configuracion",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("clave", models.CharField(max_length=100, unique=True)),
                ("valor", models.TextField()),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "configuracion_sistema",
            },
        ),
        migrations.CreateModel(
            name="TareaProgramada",
            fields=[
                ("id_tarea", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=150)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("cron", models.CharField(max_length=100)),
                ("activa", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "tarea_programada",
            },
        ),
        migrations.CreateModel(
            name="BitacoraSistema",
            fields=[
                ("id_bitacora", models.AutoField(primary_key=True, serialize=False)),
                ("accion", models.CharField(max_length=200)),
                ("modulo", models.CharField(max_length=100)),
                ("detalle", models.TextField(blank=True, null=True)),
                ("ip", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bitacoras",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "bitacora_sistema",
            },
        ),
        migrations.CreateModel(
            name="EjecucionTarea",
            fields=[
                ("id_ejecucion", models.AutoField(primary_key=True, serialize=False)),
                ("fecha_inicio", models.DateTimeField()),
                ("fecha_fin", models.DateTimeField(blank=True, null=True)),
                ("estado", models.CharField(max_length=50)),
                ("resultado", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tarea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ejecuciones",
                        to="audit.tareaprogramada",
                    ),
                ),
            ],
            options={
                "db_table": "ejecucion_tarea",
            },
        ),
    ]
