# Generated by Django 5.2.12 on 2026-05-30 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                ("id_empresa", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=255)),
                ("codigo_bbv", models.CharField(max_length=50, unique=True)),
                ("sigla", models.CharField(blank=True, max_length=20, null=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("sitio_web", models.URLField(blank=True, null=True)),
                ("activa", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "empresa",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="SectorEmpresa",
            fields=[
                ("id_sector", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Sector Empresa",
                "verbose_name_plural": "Sectores Empresa",
                "db_table": "sector_empresa",
            },
        ),
        migrations.CreateModel(
            name="ReporteFinanciero",
            fields=[
                ("id_reporte", models.AutoField(primary_key=True, serialize=False)),
                ("gestion", models.IntegerField()),
                (
                    "tipo_periodo",
                    models.CharField(
                        choices=[("TRIMESTRAL", "Trimestral"), ("ANUAL", "Anual")],
                        max_length=20,
                    ),
                ),
                ("trimestre", models.IntegerField(blank=True, null=True)),
                ("fecha_publicacion", models.DateField(blank=True, null=True)),
                ("fecha_descarga", models.DateTimeField(blank=True, null=True)),
                ("url_pdf", models.URLField(max_length=500)),
                (
                    "nombre_archivo",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "ruta_archivo",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "hash_archivo",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("tamano_archivo", models.BigIntegerField(blank=True, null=True)),
                (
                    "estado_procesamiento",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("DESCARGADO", "Descargado"),
                            ("PROCESADO", "Procesado"),
                            ("ERROR", "Error"),
                        ],
                        default="PENDIENTE",
                        max_length=50,
                    ),
                ),
                ("mensaje_error", models.TextField(blank=True, null=True)),
                ("datos_extraidos_json", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reportes",
                        to="financials.empresa",
                    ),
                ),
            ],
            options={
                "db_table": "reporte_financiero",
            },
        ),
        migrations.CreateModel(
            name="ArchivoProcesado",
            fields=[
                ("id_archivo", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_archivo", models.CharField(max_length=255)),
                ("ruta_archivo", models.CharField(max_length=500)),
                (
                    "hash_archivo",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("tipo_archivo", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reporte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archivos",
                        to="financials.reportefinanciero",
                    ),
                ),
            ],
            options={
                "db_table": "archivo_procesado",
            },
        ),
        migrations.AddField(
            model_name="empresa",
            name="sector",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="empresas",
                to="financials.sectorempresa",
            ),
        ),
    ]
