# Generated by Django 5.2.12 on 2026-05-30 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("financials", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ArchivoProcesado",
        ),
    ]
