# Generated by Django 5.2.12 on 2026-05-30 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("financials", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcesoCarga",
            fields=[
                ("id_proceso", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tipo_proceso",
                    models.CharField(
                        choices=[
                            ("descarga", "Descarga"),
                            ("extraccion", "Extracción"),
                            ("limpieza", "Limpieza"),
                            ("calculo", "Cálculo"),
                            ("carga_completa", "Carga Completa"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("en_proceso", "En Proceso"),
                            ("exitoso", "Exitoso"),
                            ("fallido", "Fallido"),
                        ],
                        default="pendiente",
                        max_length=50,
                    ),
                ),
                ("fecha_inicio", models.DateTimeField(auto_now_add=True)),
                ("fecha_fin", models.DateTimeField(blank=True, null=True)),
                ("detalle", models.TextField(blank=True, null=True)),
                ("mensaje_error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="procesos",
                        to="financials.empresa",
                    ),
                ),
                (
                    "reporte",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="procesos",
                        to="financials.reportefinanciero",
                    ),
                ),
            ],
            options={
                "db_table": "proceso_carga",
            },
        ),
    ]
