# Generated by Django 5.2.12 on 2026-05-31 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="last_name",
        ),
        migrations.AddField(
            model_name="usuario",
            name="nombre",
            field=models.CharField(default="", max_length=100),
        ),
    ]
