# Generated by Django 5.2.12 on 2026-06-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_usuario_first_name_remove_usuario_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='apellido_paterno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ci',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
