# Generated by Django 5.2.12 on 2026-05-30 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("financials", "0002_delete_archivoprocesado"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchivoProcesado",
            fields=[
                ("id_archivo", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_archivo", models.CharField(max_length=255)),
                ("ruta_archivo", models.CharField(max_length=500)),
                ("hash_archivo", models.CharField(max_length=255)),
                ("tipo_archivo", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reporte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archivos_procesados",
                        to="financials.reportefinanciero",
                    ),
                ),
            ],
            options={
                "db_table": "archivo_procesado",
            },
        ),
    ]
